"""empty message

Revision ID: 35ebcf5dba9a
Revises: 9a005cf3489d
Create Date: 2020-09-10 17:44:22.151513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35ebcf5dba9a'
down_revision = '9a005cf3489d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendee', sa.Column('verification_image', sa.Text(), nullable=False))
    op.drop_constraint(None, 'favourites', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'favourites', 'event', ['event_id'], ['id'])
    op.drop_column('attendee', 'verification_image')
    # ### end Alembic commands ###
