"""empty message

Revision ID: 9a005cf3489d
Revises: 05b90c63c393
Create Date: 2020-09-10 02:48:05.062640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a005cf3489d'
down_revision = '05b90c63c393'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favourites', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'favourites', 'event', ['event_id'], ['id'])
    # ### end Alembic commands ###
