"""empty message

Revision ID: eeb33121594a
Revises: 35ebcf5dba9a
Create Date: 2020-09-10 17:45:55.602664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeb33121594a'
down_revision = '35ebcf5dba9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendee', sa.Column('verification_image', sa.Text(), nullable=True))
    op.drop_constraint(None, 'favourites', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'favourites', 'event', ['event_id'], ['id'])
    op.drop_column('attendee', 'verification_image')
    # ### end Alembic commands ###
